/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadgeRouteImport } from './routes/badge'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as DocsRouteImport } from './routes/docs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeRoute = BadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badge': typeof BadgeRoute
  '/button': typeof ButtonRoute
  '/docs': typeof DocsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badge': typeof BadgeRoute
  '/button': typeof ButtonRoute
  '/docs': typeof DocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badge': typeof BadgeRoute
  '/button': typeof ButtonRoute
  '/docs': typeof DocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/badge' | '/button' | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/badge' | '/button' | '/docs'
  id: '__root__' | '/' | '/badge' | '/button' | '/docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgeRoute: typeof BadgeRoute
  ButtonRoute: typeof ButtonRoute
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge': {
      id: '/badge'
      path: '/badge'
      fullPath: '/badge'
      preLoaderRoute: typeof BadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgeRoute: BadgeRoute,
  ButtonRoute: ButtonRoute,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
